name: workflow jvm
on:
  push:
    paths: ['.github/**','jvm/**']
jobs:
  run-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: |
            cd jvm
            ./gradlew test jacocoTestReport
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./jvm/build/reports/jacoco/test/jacocoTestReport.xml
            verbose: true
