name: workflow dotnet
on:
  push:
    paths: ['.github/**','jvm/**']
jobs:
  run-tests:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          dotnet-version: ['5.0.x', '3.0', '3.1.x']
      defaults:
        run:
          working-directory: ./dotnet
      steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
          uses: actions/setup-dotnet@v1.7.2
          with:
            dotnet-version: ${{ matrix.dotnet-version }}
        - name: Install dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --configuration Release --no-restore
        - name: Test
          run: dotnet test --no-restore --verbosity normal
